services:
  - type: web
    name: nagano-travel-api
    env: node
    region: singapore
    plan: free
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3003
    healthCheckPath: /api/health
